language: python

services:
  - docker

before_script:
  - docker pull sslhep/servicex-transformer:rabbitmq || true

script:
  - docker build --cache-from sslhep/servicex-transformer:rabbitmq -t sslhep/servicex-transformer:rabbitmq .
  - docker run sslhep/servicex-transformer:rabbitmq bash -c "source /home/atlas/.bashrc && flake8"
  - docker run sslhep/servicex-transformer:rabbitmq bash -c "source /home/atlas/.bashrc && pytest -v --rootdir /home/atlas"
